'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {io}=require('socket.io-client');
const {createApp}=require('../server');
function rpc(socket,event,payload={}){return new Promise((resolve,reject)=>socket.timeout(3000).emit(event,payload,(e,r)=>e?reject(e):resolve(r)));}
const once=(s,e)=>new Promise(r=>s.once(e,r));
test('실시간 수업의 권한, 제출 잠금, 마감, 복구, 방 분리',async t=>{
 const instance=createApp({teacherPin:'9876'});await new Promise(r=>instance.server.listen(0,'127.0.0.1',r));
 const url='http://127.0.0.1:'+instance.server.address().port,clients=[];
 t.after(async()=>{clients.forEach(s=>s.disconnect());await new Promise(r=>instance.io.close(r));});
 async function connect(){const s=io(url,{transports:['websocket'],reconnection:false});clients.push(s);await once(s,'connect');return s;}
 async function teacher(){const s=await connect(),login=await rpc(s,'teacher_login',{pin:'9876'});assert(login.ok);const room=await rpc(s,'create_room');assert(room.ok);return {s,auth:login.auth,code:room.state.roomCode};}
 const a=await teacher();assert.match(a.code,/^\d{4}$/);
 await t.test('PIN 및 교사 권한',async()=>{const s=await connect();assert.equal((await rpc(s,'teacher_login',{pin:'wrong'})).ok,false);assert.equal((await rpc(s,'create_room')).ok,false);assert.equal((await rpc(s,'close_poll',{question:1})).ok,false);});
 const students=[];
 await t.test('27명 동시 입장 및 접속 인원',async()=>{await Promise.all(Array.from({length:27},async(_,i)=>{const s=await connect(),r=await rpc(s,'student_join',{roomCode:a.code,studentNumber:i+1});assert(r.ok);assert.equal(r.state.results,undefined);students[i]={s,token:r.studentToken};}));const r=await rpc(a.s,'teacher_resume',{auth:a.auth,roomCode:a.code});assert.equal(r.state.connected,27);});
 await t.test('중복 번호, 범위, 교사 명령 거부',async()=>{const duplicate=await connect();assert.equal((await rpc(duplicate,'student_join',{roomCode:a.code,studentNumber:12})).ok,false);assert.equal((await rpc(duplicate,'student_join',{roomCode:a.code,studentNumber:28})).ok,false);assert.equal((await rpc(students[0].s,'next_question',{question:1})).ok,false);assert.equal((await rpc(students[0].s,'teacher_resume',{auth:a.auth+'bad',roomCode:a.code})).ok,false);});
 await t.test('생물·이유 검증 및 선택적 40자 의견',async()=>{const s=students[0].s;assert.equal((await rpc(s,'student_submit',{question:1,organism:'소나무',reason:0})).ok,false);assert.equal((await rpc(s,'student_submit',{question:1,organism:'없는생물',reason:1})).ok,false);assert.equal((await rpc(s,'student_submit',{question:1,organism:'소나무',reason:1,comment:'가'.repeat(41)})).ok,false);const teacherUpdate=once(a.s,'teacher_state');const r=await rpc(s,'student_submit',{question:1,organism:'소나무',reason:2,comment:'<img src=x onerror=alert(1)>'});assert(r.ok);assert.equal(r.state.results,undefined);const update=await teacherUpdate;assert.equal(update.results[0].organisms[0].reasons[1].count,1);assert.equal(update.results[0].comments[0].comment,'<img src=x onerror=alert(1)>');});
 await t.test('재제출 금지 · 동시 제출 원자성',async()=>{const payload={question:1,organism:'소나무',reason:1};assert.equal((await rpc(students[0].s,'student_submit',payload)).ok,false);const pair=await Promise.all([rpc(students[1].s,'student_submit',payload),rpc(students[1].s,'student_submit',payload)]);assert.equal(pair.filter(r=>r.ok).length,1);assert.equal(pair.find(r=>r.ok).state.myResponse.comment,'');});
 await t.test('제출 후 새 연결 복구 및 이전 소켓 권한 회수',async()=>{const fresh=await connect();const r=await rpc(fresh,'student_join',{roomCode:a.code,studentNumber:1,studentToken:students[0].token});assert(r.ok);assert(r.state.submitted);assert.equal(r.state.myResponse.reason,2);assert.equal((await rpc(fresh,'student_submit',{question:1,organism:'토끼',reason:1})).ok,false);assert.equal((await rpc(students[0].s,'student_submit',{question:1,organism:'토끼',reason:1})).ok,false);students[0].s=fresh;});
 await t.test('다른 학생에게 제출 중 결과가 누출되지 않음',async()=>{const r=await rpc(students[2].s,'student_join',{roomCode:a.code,studentNumber:3,studentToken:students[2].token});assert.equal(r.state.results,undefined);assert.equal(r.state.responses,undefined);assert.equal(r.state.comments,undefined);});
 await t.test('전원 제출 전 마감 · 미제출 즉시 결과 · 추가 제출 거부',async()=>{assert.equal((await rpc(a.s,'next_question',{question:1})).ok,false);const push=once(students[2].s,'student_state');const r=await rpc(a.s,'close_poll',{question:1});assert(r.ok);assert.equal(r.state.question,1);assert.equal(r.state.results[0].submitted,2);assert.equal(r.state.results[0].missing,25);const student=await push;assert.equal(student.questionState,'CLOSED');assert.equal(student.submitted,false);assert.equal(student.results.submitted,2);assert.equal(student.results.organisms[0].reasons,undefined);assert.equal(student.results.comments,undefined);assert.equal((await rpc(students[2].s,'student_submit',{question:1,organism:'소나무',reason:1})).ok,false);});
 await t.test('늦은 입장 · 교사 이동 전 현재 결과 유지',async()=>{const s=await connect();students[3].s.disconnect();await new Promise(r=>setTimeout(r,20));const r=await rpc(s,'student_join',{roomCode:a.code,studentNumber:4});assert(r.ok);assert.equal(r.state.question,1);assert.equal(r.state.questionState,'CLOSED');students[3]={s,token:r.studentToken};});
 await t.test('교사만 다음 요청 이동 · 미제출 학생도 참여',async()=>{const push=once(students[2].s,'student_state');assert((await rpc(a.s,'next_question',{question:1})).ok);const next=await push;assert.equal(next.question,2);assert.equal(next.questionState,'OPEN');assert.equal(next.submitted,false);assert.equal(next.results,undefined);assert.equal((await rpc(a.s,'next_question',{question:1})).ok,false);assert((await rpc(students[2].s,'student_submit',{question:2,organism:'토끼',reason:2})).ok);});
 await t.test('서로 다른 수업방 분리',async()=>{const b=await teacher();assert.notEqual(a.code,b.code);const s=await connect();assert((await rpc(s,'student_join',{roomCode:b.code,studentNumber:1})).ok);assert((await rpc(s,'student_submit',{question:1,organism:'곰팡이',reason:3})).ok);const bState=(await rpc(b.s,'teacher_resume',{auth:b.auth,roomCode:b.code})).state;assert.equal(bState.results[0].submitted,1);const aState=(await rpc(a.s,'teacher_resume',{auth:a.auth,roomCode:a.code})).state;assert.equal(aState.results[0].submitted,2);assert.equal(aState.results[1].submitted,1);assert.equal((await rpc(b.s,'teacher_resume',{auth:b.auth,roomCode:a.code})).ok,false);});
 await t.test('3번 종료 및 전체 결과',async()=>{assert((await rpc(a.s,'close_poll',{question:2})).ok);assert((await rpc(a.s,'next_question',{question:2})).ok);assert((await rpc(students[4].s,'student_submit',{question:3,organism:'곰팡이',reason:3,comment:'낙엽이 많아서'})).ok);assert((await rpc(a.s,'close_poll',{question:3})).ok);assert.equal((await rpc(a.s,'next_question',{question:3})).ok,false);const push=once(students[4].s,'student_state');const end=await rpc(a.s,'class_end');assert(end.state.ended);assert((await push).ended);assert.equal(end.state.results.length,3);assert.equal((await rpc(students[5].s,'student_submit',{question:3,organism:'매',reason:2})).ok,false);});
 await t.test('초기화와 기존 코드 만료',async()=>{const old=a.code;const push=once(students[4].s,'room_removed');const r=await rpc(a.s,'reset_room');assert(r.ok);await push;assert.notEqual(r.state.roomCode,old);assert.equal(r.state.results[0].submitted,0);assert.equal((await rpc(students[4].s,'student_join',{roomCode:old,studentNumber:5})).ok,false);});
 await t.test('HTTP 경로 · 보안 헤더 · 상태 확인',async()=>{for(const route of ['/','/teacher','/student','/socket.io/socket.io.js','/assets/haebit-01.png','/health']){const r=await fetch(url+route);assert.equal(r.status,200);if(!route.startsWith('/socket.io/'))assert(r.headers.get('content-security-policy'));}});
});
test('서버 재시작 시 이전 방과 토큰이 유효하지 않음, PIN 미설정 차단',async()=>{
 const instance=createApp({teacherPin:''});await new Promise(r=>instance.server.listen(0,'127.0.0.1',r));const s=io('http://127.0.0.1:'+instance.server.address().port,{transports:['websocket']});await once(s,'connect');try{assert.equal((await rpc(s,'teacher_login',{pin:''})).ok,false);assert.equal((await rpc(s,'teacher_resume',{auth:'previous',roomCode:'1111'})).ok,false);assert.equal((await rpc(s,'student_join',{roomCode:'1111',studentNumber:1})).ok,false);}finally{s.disconnect();await new Promise(r=>instance.io.close(r));}
});
